id: IA1A341AF
legacy_id: P006601
ocr_import_info:
  bdrc_scan_id: W1KG23091
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T15:41:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T07:18:07.778455+00:00'
last_modified: 2022-08-27 15:20:24.217404
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG23091
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG23091
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་འཇུག་རྣམ་བཤད་ཐེག་ཆེན་ཆོས་ཀྱི་རྒྱ་མཚོ།
  author: དཔའ་བོ ༠༢་གཙུག་ལག་འཕྲེང་བ།
statistics:
  ocr_word_mean_confidence_index: 0.9233261705680055
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG23138:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG23138
      total_pages: 602
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG23138.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9395821379168163
    legacy_id: v002
  I1KG23137:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG23137
      total_pages: 642
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG23137.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.90824638142126
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
