id: IA1A341AF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:45:27+00:00'
last_modified: '2022-06-08T05:33:07.854512+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23091
  title: སྤྱོད་འཇུག་རྣམ་བཤད་ཐེག་ཆེན་ཆོས་ཀྱི་རྒྱ་མཚོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B586:
      image_group_id: I1KG23137
      title: ''
      total_pages: 642
      order: 1
      base_file: B586.txt
    31DC:
      image_group_id: I1KG23138
      title: ''
      total_pages: 602
      order: 2
      base_file: 31DC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
